---
environment:
  COLOR: silver
pipeline:
  unit_test: deploy
profiles:
  unit_test:
    script: ./statictest.sh
    output:
      - change_artifact
  deploy:
    input:
      - change_artifact
    script: ./deploy_application.sh
