# /config/solano.yml
---
environment:
  COLOR: red
pipeline:
  fetch:
    unit_test:
      deploy
steps:
  fetch:
    script: ./tarfile.sh
    output:
      - artifact.tar
  unit_test:
    input:
      - artifact.tar
    script: ./statictest.sh
    output:
      - artifact.tar
  deploy:
    input:
      - artifact.tar
    script: ./deploy_application.sh